:PROPERTIES:
:ID:       6d754801-89a1-41ec-a8ce-47fbc3e24adf
:END:
#+title: career

[[id:c1cbc82c-ad99-4ae6-80a8-a9d83d2e71b8][careerNetworking]]

** module 29 careers: personal branding
*** 29.1 Understanding personal branding

Understanding personal branding
10 minutesEstimated completion time
Learning Objective

By the end of this lesson, you should be able to explain the purpose of personal branding.
Overview

Most employers will spend only a few seconds looking at your resume or an online profile, so it's vital that you make a good first impression. This module covers how to present yourself as positively as possible on paper and online. You will learn about the importance of personal branding and ways to effectively promote yourself to companies during your job search.
Image of a woman with a star

What is personal branding?

Jeff Bezos defines a person's brand as "what other people say about you when you're not in the room." Think about that for a moment. How would people describe you? Would this description differ if it came from close friends versus from a stranger who can access only your social media platforms?

Often, employers fit into this latter category. Because they don't know you, they rapidly make assumptions about you based on the few resources at their disposal: your resume and public-facing online profiles.

You might be wondering why you are learning about personal branding right now.

It's important to start networking as soon as you can. But as soon as you start networking, employers are going to start asking for your resume and looking at your LinkedIn profile, so you want those materials to be as polished as possible.

Although you'll develop your resume and LinkedIn profile throughout this program and your career as you continue to complete projects, you can still start outlining and refining them now. That way, they'll be ready the moment that you need to use them, and, in the meantime, you'll look good online.

While this module only requires you to polish your professional branding assets, remember that the majority of employers also review your social media profiles during the hiring process. So it's important to ensure that all of your public-facing profiles are employer-friendly.
*** 29.2 Building a resume
Building a resume
2 hoursEstimated completion time
Learning Objective

By the end of this lesson, you should be able to build a resume tailored to your experiences using a Thinkful resume template.
Overview

This lesson covers how employers review resumes, what you should include in your resume, how to tailor your resume to every job listing, and how to make your resume attractive and easy to read.
Key Terms

Applicant tracking systems
    Software applications that electronically scan your resume for certain keywords and phrases to see if you're a match for a specific job listing

Why is a resume important?

In most cases, your resume is an employer's first introduction to you. Employers use it to determine whether or not they want to interview you for a specific job opening at their company. And they often make this decision in just a few seconds.

There's good news, though. There's a lot that you can do to ensure that your resume highlights the qualifications that employers are looking for—and showcases you in the best way possible.
Applicant tracking systems

Before you start to write your resume, it's helpful to understand what applicant tracking systems are, how they work, and why they're important. An applicant tracking system, or ATS, is a software application that electronically scans your resume for certain keywords and phrases to see if you're a match for a specific job listing.

Employers often use an ATS during the first stage of the hiring process to filter out resumes (and, therefore, candidates) who don't seem like they're qualified for the job that they're applying to.

As you develop your resume, you want to ensure you are using a format that is ATS-friendly and allows the system to easily and correctly scan your document. The templates you will use for this assessment are designed with an ATS in mind, including clearly labeled sections, easy-to-read fonts, reverse chronological order, and no columns or tables. Additionally, you want to have the appropriate keywords, skills, and phrases within your resume to align you with the job qualifications.

In the next section of this lesson, you'll learn how to effectively tailor each section of your resume to specific job listings and industries—ensuring that everything that you include in your resume is intentional, relevant, and transferable. In other words, you'll write your resume for where you want to go versus where you have been. The skills and experience that you include should be either directly related to the job that you're applying to or be something generic that can still be used in the job that you're applying to.
Resume components

Although every resume is different, all resumes should include most or all of the sections described in this lesson.

Resumes are subjective and no matter who you show them to, you will get slightly different advice about how to revise them. The areas laid out below and the templates you will use to create your resume were developed by certified resume writers and career development professionals. The resume you will create using these materials is designed to help you stand out in your job search.
Contact information

Always list your contact information at the top of your resume. You should make sure that your contact information includes the following items:

    Your first and last name

    Your city and state of residence (but not your full address)

    Your phone number

    Your email address. This email address should be a professional one, meaning that it includes some version of your name and has no reference to personal or unprofessional information.

    The URL to your LinkedIn, personal website or portfolio, or GitHub profile. Note that you should always use the shortened version of the URL; for example, use myurl.com instead of http://myurl.com. You can customize your LinkedIn URL or use sites like bit.ly to help here too!

Summary

After your contact information, you should include a one- to three-sentence summary that briefly tells employers who you are and what skills you offer.

To create your summary, you should do the following steps:

    Introduce yourself using the title of the job that you're applying to.

    List your relevant qualifications and skills.

    Highlight something interesting or transferable about your background.

    Don't use personal pronouns (such as I, s/he/they, and my).

This focuses your resume and immediately communicates to employers that it's worthwhile for them to continue considering you. Here's a template in action:

Full-stack software engineer proficient in using Javascript for front end and back end programming, React, HTML, CSS, API implementing, Node.JS, Express, PostgreSQL, and frameworks like Bootstrap. Problem solver with past experience developing logical and methodical solutions to scientific problems. Has a keen eye for design, allowing for development of visually pleasing and user-friendly website designs.
Skills

Next, include a list of 9 to 15 of your top relevant skills. Organize them as categorized lists, like the image below:
Categorized list of skills

In addition to technical and industry-specific skills, you can consider an Additional Skills grouping. This section would include skills like the ones you can see below:

Additional skills

    Bilingual (English and Spanish)

    Customer service

    Budget management

    Solutions-oriented

    Organization

    Time management

Projects

The projects you are working on within your Thinkful program are professional in nature and showcase the skills you are gaining in the field. They will be added to your resume to highlight this knowledge, assist with applicant tracking systems and help employers see your skills in action.

As you will see in the templates provided for this assessment, you will showcase your projects differently depending on your previous experience. Projects can be listed under experience, in a separate projects section, or referenced under education. However, no matter where the projects are listed it is important to consider the below items when highlighting your relevant project work:

    The project's name: This should describe the project. For example, the Lariat Car Rental Capstone can become Business analysis and revenue growth models: Lariat Car Rental.

    A URL for the project (if it can be viewed online): This should be hyperlinked in the resume with a word like Portfolio or Project Link.

You should also use the STAR method to list information, which is an abbreviation for Situation, Task, Action, and Result. You can see how this method would work for a resume section below:

    Situation: A one-line description of the project

    Task: What you were charged with doing to complete the project

    Action: The steps you took to complete the task, including relevant technologies and methods

    Result: The outcome of your actions (preferably with a quantifiable impact)

Tip

Because you are still developing projects within your program, for now, you should only add projects you have completed. You can continue to reference this lesson to add more projects as you go! Your resume is meant to be a living document that you are constantly updating to reflect your skills and knowledge.

Start each bullet point with an action verb, like developed, created, led, or managed. Visit this list of action verbs if you want to see more examples.
Tip

When you work on the resume project lesson, you will see example Thinkful projects that you can copy and paste into your resume. They will just need minor tweaks to mirror the work you have completed.
Experience

The purpose of your experience section is twofold. You want to show employers two things:

    That you have relevant and transferable experience

    That you don't just do your job—you get results

This means that you should be strategic about what you include. You don't need to include every past job, task, or responsibility. Rather, you should focus on your relevant and transferable accomplishments within your previous jobs.

For each past job, include the following information:

    Your job title

    The company's name

    The city and state that you worked in

    The dates that you worked that job

    A bulleted list that highlights three or four of your accomplishments

When developing bullet points for your resume, consider the following information:

    Achievement: Focus on what you achieved, not what you were assigned. For example, "Drove the high-quality and on-time completion of 14 software development projects, using both predictive and adaptive development strategies," is a lot more impressive than "Responsible for project management."

    Impact: Try to quantify your work where possible. Provide numbers to highlight the importance of certain outcomes or tasks.

    Skills: Focus on skills instead of tasks. Using strong action verbs to start each bullet allows you to highlight different skills. If possible, each bullet on your resume should start with a different action verb.

    No personal pronouns: Avoid pronouns like I, she, he, they, me, etc.

    Tense: Use present tense for current jobs and responsibilities and past tense for former jobs and things you have already accomplished.

Education

Similar to the projects section, Thinkful will be listed slightly differently on your resume depending on your past experience and education. There are clear templates and guides within the assessment section of this lesson. However, for a general guide, the education section should include any relevant secondary education studies, including Thinkful, other certifications, and university studies.

For each entry, include the following:

    The type of degree that you earned or the major topic of your study

    The school's name

    The years that you studied at that school, or just the year that you graduated

    Your GPA, if it's 3.5 or above.

    Any relevant awards, honors, fellowships, or classes

Because your Thinkful program is probably more relevant to potential employers than your other education, it's okay to add some additional details in your Thinkful entry. Here's an example of an educational summary for your Thinkful program:

Thinkful (Online)

Certificate, UX/UI | 03/2024 - 07/2024

    Conducted user surveys and interviews; leveraged data to develop personas, empathy and journey maps, user stories, and flows in order to make informed design decisions.

    Utilized the double-diamond process and design sprint while creating effective case studies to showcase findings and design decisions with clients and stakeholders.

Tip

Remember, the language above is only for the UX/UI Certificate. You'll need to change the language above to fit the work you completed in your certificate program.
Resume style guidelines

After you finalize all of the necessary content for your resume, the next thing that you should do is style it in a professional, easy-to-read format. Although there is lots of room for creativity and personal preference, below are some guidelines that you should always follow.
Length

Many employers spend less than a minute looking at your resume, so you should keep it short. One page is ideal. (And no stretching the margins!) If you truly need the space, you can go up to two pages—but only if everything on the two pages is relevant.

Because employers scan resumes rather than reading them in full, you want whatever their eyes land on to be something that makes them interested in you. And keeping your resume one or two pages long forces you to cut the fluff. For example, you don't need to include any work experience from more than a decade ago.
Order

The majority of people read from top to bottom, so it's important to showcase your most attractive information first. Your resume components should be listed reverse chronologically by section. Here's an example of how to order your resume:

    Contact information

    Summary

    Skills

    Projects (if any)

    Experience or education (whichever is going to be most attractive to employers)

    Experience or education (whichever you didn't list first)

Font

The font style and size you choose matter when developing a resume because they help with both readability and allowing your resume to be scanned by an ATS.
Typeface

Thinkful template resumes will be done in Arial (Sans Serif) or Cambria (Serif) font. These fonts are ATS-friendly and preferred by recruiters.
Size

The main text of your resume should be between size 10 and size 12. Size 11 font is ideal. It also can be a good option to use a font size that's two points larger than your main text for headings; this can make your resume easy for employers to navigate. You can also select an even bigger font size for your name so that it stands out on your resume.
Spelling and grammar

Before submitting your resume to employers, double-, triple-, and quadruple-check it for spelling and grammar errors. It helps to read it aloud, have friends and family proofread it, and use free tools like Grammarly to guarantee that your resume is error-free.
Consistency

Whatever you choose to do, be consistent. One of the most common resume pitfalls is a lack of consistency. Unfortunately, a messy resume is an easy way to lose a job before ever being considered.

Review your typefaces, font sizes, heading styling and formatting, margin alignments, dates, and bullet point styles. Ensure that all of the styles you apply are consistent throughout your resume. The Thinkful template you will use for this assessment will help with this!

Remember, the goal of your resume is to get the employer interested enough to start a conversation with you. When the conversation starts, your resume becomes less important; then, it's your job to speak intelligently about your experience.
Supplementary resources

    List of action verbs

    Resume checklist

    ATS checkers for your resume: Jobscan and SkillSyncer

    Grammarly

    Resume template program verbiage: Use this document to copy and paste information for your summary, skills, projects, and education section.
*** 29.3 Resume project
*** 29.4 Building a LinkedIn profile
Building a LinkedIn profile
2 hoursEstimated completion time
Learning Objective

By the end of this lesson, you should be able to create an effective LinkedIn profile.
Overview

LinkedIn is the world's largest professional networking platform. This lesson covers why knowing how to use LinkedIn is important and describes how to create a robust LinkedIn profile for your job search.
What is a LinkedIn profile?

Your LinkedIn profile is essentially an online version of your resume, but better! It's interactive, follows a standardized format, isn't limited to a couple of pages, and allows you to attach work samples.

95% of employers use LinkedIn as their go-to platform to source talent, which means that it's essential for job seekers to have a complete LinkedIn profile. Additionally, having a complete profile makes you 40 times more likely to receive job opportunities.

Once you have a profile, you can use LinkedIn to do the following job-searching tasks:

    Find and apply to job listings

    Grow your professional network

    Find someone to conduct an informational interview with

    Share and find work-related news and tips

    Share your professional history and projects with employers

    Get recruited

LinkedIn profile components

Happily, because LinkedIn profiles are similar to resumes, you're able to copy and paste a lot of the information that's on your resume, which makes creating a profile easy. There are, however, some additional components and considerations, which you can review below.
Tip

Before you start making lots of updates to your profile, it's smart to turn off your activity broadcast so that LinkedIn doesn't notify your contacts each time you make a change to your profile.
Custom URL

When polishing your LinkedIn profile, the first thing to do is create a customized URL for your profile. Customized URLs look cleaner on your resume and make it easier for employers to find your profile.

Ideally, your customized URL should follow the naming convention "FirstName-LastName," or something similar. If that's unavailable, choose a variation of your name that's still recognizable, simple, and professional.

To customize your LinkedIn URL, follow the steps in this link.
Profile photo

One of the first steps in completing your LinkedIn profile is to add a profile photo. When you have a LinkedIn profile photo, you can get up to 21 times more profile views than users without a photo.

You want your profile photo to showcase the best, most professional version of yourself. The photo should reflect what you might look like when you go in for an interview and should be representative of what you look like currently. Here are some guidelines that your LinkedIn profile photo should adhere to:

    Smile. Like everyone else, employers prefer working with people who are friendly and fun to be around. A smile is the best way to signal that you are.

    Be professional. No sunglasses, hats, or potentially offensive logos.

    Be in focus. Either use a neutral, nondescript background or a camera lens that blurs your background so that you're the main focus of the photo and nothing distracts from you. For the same reason, you should be the only person in the photo.

    Opt for high quality. Your photo doesn't need to be taken by a professional photographer, but it should be high quality, have sharp (not fuzzy) focus, and be well lit. (No selfies!)

Two example LinkedIn profile pics
Background photo

The next thing to consider is customizing your background photo. This is the long photo that's displayed at the top of your LinkedIn profile. While it's okay to keep the generic image, uploading a background image can add visual interest to your profile and help it be more memorable to viewers.

If you do choose to customize your background photo, try to choose one that's the same color scheme as your portfolio or resume. You can also use your background photo to keep a consistent brand, or you can pick an image that reflects your location or the industry that you're transitioning into. Just keep it professional, high quality, and simple—you want it to enhance your LinkedIn profile, not be a distraction.

You can either use your own image or something that you find online, like from the free photo-sharing site Unsplash. Below are a few ideas.

A skyline of the city where you live:
A skyline photo as an example LinkedIn background image

A solid color that matches your portfolio or resume's color scheme:
Example background color that can be used in a LinkedIn profile.

A graphic that reflects your industry:
Colorful lines of code that can be used as an example background image on LinkedIn.

Headline

Next is your headline. This is the copy that you see below your name. LinkedIn automatically makes your headline the title of your current job. However, you can update it to reflect the job that you want, such as, "Frontend Developer," "Technical Project Manager," or "Digital Marketer."

To avoid hiring bias, don't use phrases like "open to new opportunities" in your headline.
About

Like the summary section of your resume, the LinkedIn About section is an opportunity to control your story. Be strategic about what you write in this section, knowing that how you describe yourself influences the way that viewers think about you.

Are you a former technical support person, or are you a software engineer with expertise in hardware and networking? Are you a marketer turned designer, or are you a UX designer who is well-versed in what customers want?

Generally, you can use the summary section of your resume as a starting point. But because you're not limited on space, it's okay to expand. For example, it's helpful to say what motivates you, share a relevant personal anecdote, or identify your top skills. You can demonstrate that you're someone who works well on a team, mention impressive projects, or provide links to your portfolio.

Finally, write in first person. Viewers know that you're filling out your own LinkedIn profile, so it's a lot more natural to use language that reflects that. Here's an example of an interesting LinkedIn About section:

Hi! I'm Amy and I tend to flex my right-brain muscles more often than not. In the fifth grade, I took a bunch of my mom's magazines, clipped them up, and created a student newsletter because our class didn't have one. It was poorly constructed, stapled together on wide-ruled, loose-leaf notebook paper, but it became really popular—so much so that other students in my class started creating their own zines to compete with mine.

My fifth-grade teacher was impressed by the engagement and told me that I was an "innovative" 10-year-old that should hold on tight to her creative skills. She also let me skip gym class so that I could start producing the class newsletter with Microsoft Word. (Shout out to ClipArt!)

I am a digital media entrepreneur, marketer, and full-stack web developer who lives at the intersection of technology, art, and content creation. I currently work in marketing for one of the world's largest technology companies and spend my time outside the office empowering women through my digital platform, mentoring, and service work.

My specialties are digital marketing, growth hacking, SEO, content creation, blogging, web design, full-stack web development, HTML, CSS, JavaScript, JQuery, Bootstrap, AngularJS, ReactJS, Drupal, UX/UI Design, Adobe Creative Suite (Photoshop, Illustrator, InDesign), design principles, color theory, wireframing, and digital media.
Experience

Your LinkedIn Experience section should mirror the experience section on your resume.

While you need to manually write in your job title, company name, and location, and select your start and end dates, it's best to copy and paste the bulleted accomplishments on your resume for that job. LinkedIn doesn't have formatting options, so you can use hyphens (-) or dots (•) for bullets. When you finish adding entries, cross-reference them with the entries on your resume to ensure that they match.

It's true that you have more space on your LinkedIn profile than on your resume, but that doesn't mean that an employer's attention is infinite. Resist the temptation to overload your profile with unnecessary details or jobs that you had more than a decade ago. If you do choose to add more detail to your LinkedIn profile, it should be by adding accomplishments that are relevant to the job that you want but didn't have room for on your one-page resume.
Education

Like your Experience section, your LinkedIn Education section should match the education entries on your resume.
Including Thinkful in your LinkedIn profile

You should list your Thinkful experience in either the Experience or Education section of your profile—not both. Below are best practices for listing it in either section.
Including Thinkful in the Experience section of your LinkedIn profile

On LinkedIn, you're unable to reorder your sections and projects are not prominently displayed. For this reason, it can be helpful to list your Thinkful experience in the Experience section of your LinkedIn profile.

For your title, write the title of the program that you're in or that you're still in training; for example, "Digital Marketing Program" or "Data Scientist in Training." Leave the employment type blank (or "-"). And write "Thinkful" as the company name.

Then, in the description of your Thinkful Experience entry, add the details of your projects, making sure that you list all of the skills and tools that you used. When it makes sense, you should also utilize the media function that allows you to upload an image of or add a link to your Experience entry.
Including Thinkful in the Education section of your LinkedIn profile

If you include Thinkful in the Education section of your LinkedIn profile, type "Thinkful" for the school, "Certificate" for the degree, and the title of your program for the Field of Study. For example, "UX/UI Design" or "Product Management." Include the same information that you would include in the Experience section—your projects, skills, and so on. When appropriate, use the media function. Don’t include the word “bootcamp” in your description, as some employers have a bias against bootcamp grads.
Skills & Endorsements

In the Skills & Endorsements section, list the individual skills, tools, and abilities that you have. You can include up to 50, but you should focus on the ones that are relevant to the job that you want (likely the ones that are on your resume).

Order them from most to least relevant. Then, ask your Thinkful peer and LinkedIn friends to endorse you for these skills (it helps if you endorse their skills too).

There's some debate about whether this section is useful. However, at a glance, these endorsements make you seem more credible. As well, these skills make your profile more searchable in general, and LinkedIn uses these skills endorsements to boost your search ranking in LinkedIn searches.
Recommendations

Since you're probably new to your chosen field, having someone vouch for you can be incredibly valuable.

Your mentor is a good person to ask for a recommendation because they can verify that you've mastered the skills of your program before you graduate. A peer who you've collaborated with on a project, or someone who can speak to your professional skills, might also be good people to ask.
Miscellaneous LinkedIn sections

You might notice that there are a few more sections available to you on your LinkedIn profile, like Volunteer Experience. It's not necessary to include all of these sections, but inspect them all so that you know what's available to you and add any that add relevant value to your profile.
LinkedIn connections

Something to think about is how many people you're connected to on LinkedIn. The more connections that you have, the easier it is for you to get introductions to a company, and the easier it is for employers to find your profile. So be intentional.

Search for and connect with past and current coworkers, past and current classmates, your Thinkful community, family, friends, and people you meet at networking events. LinkedIn also helps you find people to connect. Just click the My Network link in the top navigation. When the new page loads, you'll see a variety of people you may know.

LinkedIn is far less personal than other social media platforms, and it is intended for networking. So, it's okay to extend and accept invitations to connect from other LinkedIn users, even if they're strangers.
Supplementary resources

    Exemplary LinkedIn Profiles to Inspire You

    How to Make Your LinkedIn Photo Stand Out

    How to Guard Your Profile Against LinkedIn Resume Assistant

    5 Templates That'll Make Writing the Perfect LinkedIn Summary a Breeze

    Contacting a Hiring Manager on LinkedIn
*** 29.5 LinkedIn project
*** 29.6 Building your GitHub profile
Building your GitHub profile
2 hoursEstimated completion time
Learning Objective

By the end of this lesson, you'll be able to create an effective GitHub profile.
Overview

Like any other marketing material, it's important to make sure that your GitHub profile represents the best version of you and what you have to offer. This lesson covers the GitHub features that you should pay attention to during your job search.

As you may recall, GitHub is a platform that hosts code for version control and collaboration. There are many ways to use GitHub for software development specifically, but it's also a versatile platform that a variety of tech professionals use.

And it's a powerful tool for your job search as well. Remember, most employers search candidates' online profiles before making a hiring decision.

GitHub can boost your desirability as a candidate, particularly when you create a robust profile, use it regularly, and push contributions often—both during the program and in your job search. In fact, an active, robust, and well-organized GitHub can often get you an interview over a candidate with a slightly less impressive GitHub profile.
GitHub profile components

At first glance, what do employers see when they look at your GitHub profile? They see your photo, your bio, your popular and pinned repositories, and your activity. Here's how to make each stand out positively.
Photo

Your profile photo is one of the first things that people (ahem, employers) see when visiting your GitHub profile. For this reason, your photo should be employer friendly and recognizably you.

It's helpful to use the same photo that you use on your LinkedIn profile. This isn't required, but it does help establish a consistent brand and make it easier for employers to remember you.
Bio

Under your photo, you can—and should—add a bio. This can be up to 160 characters long and should focus strictly on who you are as a technical professional. Generally, a trimmed-down version of the summary on your LinkedIn profile or resume is best. Here are a few example bios:

    JavaScript developer using jQuery/React/Node.js/PostgreSQL. Experienced educator with an emphasis in informal education centers and nonprofits.

    UX designer who enjoys photography and 3D visualization. Currently pursuing UX design and frontend development projects.

    Data scientist with a background in physics and research. Passionate about using data to improve the way that businesses communicate with customers.

    Technical Project Manager

Popular repositories

Your profile also displays a selection of your popular GitHub repositories. It's best to pin a separate repository for each project that you complete. And for web development projects, it's helpful to pin a repository for both the client side and the server side of a project, such as in the following example.
Pinned repositories on a GitHub profile.

Remember to hide projects that you don't want employers to see. Although there's value in showing how you've progressed in a short period of time, you want to ensure that an employer sees your best work first.
Contribution graph

Below your popular repositories is a contribution graph, which shows your recent activity on GitHub. Specifically, this graph shows when you've committed to a repository's default branch or gh-pages branch, opened an issue, proposed a pull request, or submitted a pull request review.

Each tile represents a day. Gray tiles represent no activity, and green tiles represent activity; tiles become darker green with more activity.

This graph is perhaps the most important part of your GitHub profile, especially as you begin your job search. Most employers value candidates who are excited about their work.

And an easy way to show employers that you care about your work is by staying active on GitHub—beyond your program requirements and particularly after you graduate from your Thinkful program.

So, after you graduate, continue to refine parts of your projects and push them to GitHub. Aim for a green tile every day, from now until you get your next job.
Contribution graph summarizing pull requests, issues opened, and commits.
GitHub READMEs

All of your GitHub projects should have an accompanying README file that serves as a summary of your work. READMEs are intended to provide context for visitors looking at your project. The README should convey what your project does, why it's useful, how users can interact with it, who maintains and can contribute to it, and any other relevant background information.

Employers aren't just looking for organized and active GitHub profiles; they also want to see robust READMEs for each of your projects. This gives them context about the project that they're looking at. And it shows them that you're able to explain the concepts that you're working with, which is something that employers value.

For each of your project READMEs, include the following information, as applicable:

    Context on the problem or project (what it is and why you're doing it)

    Information on your research or user case

    How the project is intended to be used or could be used

    Various features or aspects of the project

    The technologies and tools that you used to make your project and why

    Any discoveries that you made while making the project

    Your future goals for the project

    Relevant screenshots or supplemental images

Supplementary resources

    Pinning items to your profile

    How to add screenshots to READMEs

    Data science README example

    Web development README example
