:PROPERTIES:
:ID:       8bb1d8d1-c11d-4a09-8ab4-1a8dc5995c15
:END:
#+title: LPI Linux Essentials Exam 010
#+date: [2022-05-05 Thu 09:32]

* 1 the Linux community and a career in open source

** 1.1 Linux Evolution and Popular Operating Systems
Weight: 2

Description: Knowledge of Linux development and major distributions.

Key Knowledge Areas:
    + Distributions
    + Embedded Systems
    + Linux in the Cloud

The following is a partial list of the used files, terms and utilities:
    + Debian, Ubuntu (LTS)
    + CentOS, openSUSE, Red Hat, SUSE
    + Linux Mint, Scientific Linux
    + Raspberry Pi, Raspbian
    + Android

*** Introduction
Linux's development started in 1991 by Linus Torvalds.
Linux was inspired by Unix
The Unix operating system was developed in the 1970's by AT&T Laboratories.
Linux uses the same principles and basic ideas of Unix.
Linux doesn't contain Unix code, it an independent project.
Linux is freely available, it can be used by anyone without restrictions.

*** Distributions
A Linux distribution is a bundle that consists of a Linux kernel and a selection of applications that are maintained by a company or user community.
A distribution’s goal is to optimize the kernel and the applications that run on the operating system for a certain use case or user group.
Distributions often include distribution-specific tools for software installation and system administration.
Linux distros mainly use for desktop environments, need to be easy to use.
Linux distros mainly use for servers, need to be efficient

Debian based distributions use the package manager *dpkg* to manage the software that is run on the operating system.
Most packages installed with package manager are maintained by the community.
Maintainers use the deb package format to specify how the software is installed on the operating system and how it is configured by default.
a package is a bundle of software and a corresponding configuration and documentation that makes it easier for the user to install, update and use the software.

Debian was launched by Ian Murdock in 1993.
Debian aims to provide a very reliable operating system.
Debian promotes Richard Stallman’s vision of an operating system that respects the freedoms of the user to run, study, distribute and improve the software.
This is why Debian does not provide any proprietary software by default.

Ubuntu is another Debian-based distribution worth mentioning. Ubuntu was created by Mark
Shuttleworth and his team in 2004, with the mission to bring an easy to use Linux desktop
environment. Ubuntu’s mission is to provide a free software to everyone across the world as well as
to cut the cost of professional services. The distribution has a scheduled release every six months
with a long-term support release every 2 years.

Red Hat is a Linux distribution developed and maintained by the identically named software
company, which was acquired by IBM in 2019. The Red Hat Linux distribution was started in 1994
and re-branded in 2003 to Red Hat Enterprise Linux, often abbreviated as RHEL. It is provided to
companies as a reliable enterprise solution that is supported by Red Hat and comes with software
that aims to ease the use of Linux in professional server environments. Some of its components
require fee-based subscriptions or licenses. The CentOS project uses the freely available source code
of Red Hat Enterprise Linux and compiles it to a distribution which is available completely free of
charge, but in return does not come with commercial support.

Both RHEL and CentOS are optimized for use in server environments. The Fedora project was
founded in 2003 and creates a Linux distribution which is aimed at desktop computers. Red Hat
initiated and maintains the Fedora distribution ever since. Fedora is very progressive and adopts new
technologies very quickly and is sometimes considered a test-bed for new technologies which later
might be included in RHEL. All Red Hat based distributions use the package format rpm.

The company SUSE was founded in 1992 in Germany as a Unix service provider. The first version of
SUSE Linux was released in 1994. Over the years SUSE Linux became mostly known for its YaST
configuration tool. This tool allows administrators to install and configure software and hardware,
set up servers and networks. Similar to RHEL, SUSE releases SUSE Linux Enterprise Server, which is
their commercial edition. This is less frequently released and is suitable for enterprise and
production deployment. It is distributed as a server as well as a desktop environment, with fit-for-
purpose packages. In 2004, SUSE released the openSUSE project, which opened opportunities for
developers and users to test and further develop the system. The openSUSE distribution is freely
available to download.

Independent distributions have been released over the years. Some of them are based on either Red
Hat or Ubuntu, some are designed to improve a specific propriety of a system or hardware. There are
distributions built with specific functionalities like QubesOS, a very secure desktop environment, or
Kali Linux, which provides an environment for exploiting software vulnerabilities, mainly used by
penetration testers. Recently various super small Linux distributions are designed to specifically run
in Linux containers, such as Docker. There are also distributions built specifically for components of
embedded systems and even smart devices.

*** Embedded Systems
Embedded systems are a combination of computer hardware and software designed to have a
specific function within a larger system. Usually they are part of other devices and help to control
these devices. Embedded systems are found in automotive, medical and even military applications.
Due to its wide variety of applications, a variety of operating systems based on the Linux kernel was
developed in order to be used in embedded systems. A significant part of smart devices have a Linux
kernel based operating system running on it.
Therefore, with embedded systems comes embedded software. The purpose of this software is to
access the hardware and make it usable. The major advantages of Linux over any proprietary
embedded software include cross vendor platform compatibility, development, support and no
license fees. Two of the most popular embedded software projects are Android, that is mainly used
on mobile phones across a variety of vendors and Raspbian, which is used mainly on Raspberry Pi.
*** Android
Android is mainly a mobile operating system developed by Google. Android Inc. was founded in
2003 in Palo Alto, California. The company initially created an operating system meant to run on
Linux Essentials (Version 1.6) | 1.1 Linux Evolution and Popular Operating Systems

Version: 2022-01-14 | Licensed under CC BY-NC-ND 4.0. | learning.lpi.org | 5

digital cameras. In 2005, Google bought Android Inc. and developed it to be one of the biggest mobile
operating systems.
The base of Android is a modified version of the Linux kernel with additional open source software.
The operating system is mainly developed for touchscreen devices, but Google has developed
versions for TV and wrist watches. Different versions of Android have been developed for game
consoles, digital cameras, as well as PCs.
Android is freely available in open source as Android Open Source Project (AOSP). Google offers a
series of proprietary components in addition to the open source core of Android. These components
include applications such as Google Calendar, Google Maps, Google Mail, the Chrome browser as
well as the Google Play Store which facilitates the easy installation of apps. Most users consider
these tools an integral part of their Android experience. Therefore almost all mobile devices shipped
with Android in Europe and America include proprietary Google software.
Android on embedded devices has many advantages. The operating system is intuitive and easy to
use with a graphical user interface, it has a very wide developer community, therefore it is easy to
find help for development. It is also supported by the majority of the hardware vendors with an
Android driver, therefore it is easy and cost effective to prototype an entire system.
*** Raspbian and the Raspberry Pi
Raspberry Pi is a low cost, credit-card sized computer that can function as a full-functionality
desktop computer, but it can be used within an embedded Linux system. It is developed by the
Raspberry Pi Foundation, which is an educational charity based in UK. It mainly has the purpose to
teach young people to learn to program and understand the functionality of computers. The
Raspberry Pi can be designed and programmed to perform desired tasks or operations that are part
of a much more complex system.
The specialties of the Raspberry Pi include a set of General Purpose Input-Output (GPIO) pins which
can be used to attach electronic devices and extension boards. This allows using the Raspberry Pi as
a platform for hardware development. Although it was intended for educational purposes, Raspberry
Pis are used today in various DIY projects as well as for industrial prototyping when developing
embedded systems.
The Raspberry Pi uses ARM processors. Various operating systems, including Linux, run on the
Raspberry Pi. Since the Raspberry Pi does not contain a hard disk, the operating system is started
from an SD memory card. One of the most prominent Linux distributions for the Raspberry Pi is
Raspbian. As the name suggests, it belongs to the Debian distribution family. It is customized to be
installed on the Raspberry Pi hardware and provides more than 35000 packages optimized for this
environment. Besides Raspbian, numerous other Linux distributions exist for the Raspberry Pi, like,
for example, Kodi, which turns the Raspberry Pi into a media center.
Linux Essentials (Version 1.6) | Topic 1: The Linux Community and a Career in Open Source

6 | learning.lpi.org | Licensed under CC BY-NC-ND 4.0. | Version: 2022-01-14

*** Linux and the Cloud
The term cloud computing refers to a standardized way of consuming computing resources, either by
buying them from a public cloud provider or by running a private cloud. As of 2017 reports, Linux
runs 90% of the public cloud workload. Every cloud provider, from Amazon Web Services (AWS) to
Google Cloud Platform (GCP), offers different forms of Linux. Even Microsoft, a company whose
former CEO compared Linux to cancer, offers Linux-based virtual machines in their Azure cloud
today.
Linux is usually offered as part of Infrastructure as a Service (IaaS) offering. IaaS instances are virtual
machines which are provisioned within minutes in the cloud. When starting an IaaS instance, an
image is chosen which contains the data that is deployed to the new instance. Cloud providers offer
various images containing ready to run installations of both popular Linux distributions as well as
own versions of Linux. The cloud user chooses an image containing their preferred distribution and
can access a cloud instance running this distribution shortly after. Most cloud providers add tools to
their images to adjust the installation to a specific cloud instance. These tools can, for example,
extend the file systems of the image to fit the actual hard disk of the virtual machine.

Linux Essentials (Version 1.6) | 1.1 Linux Evolution and Popular Operating Systems

Version: 2022-01-14 | Licensed under CC BY-NC-ND 4.0. | learning.lpi.org | 7

Guided Exercises
1. How is Debian GNU/Linux different from Ubuntu? Name two aspects.

2. What are the most common environments/platforms Linux is used for? Name three different
environments/platforms and name one distribution you can use for each.

3. You are planning to install a Linux distribution in a new environment. Name four things that
you should consider when choosing a distribution.

4. Name three devices that the Android OS runs on, other than smartphones.

5. Explain three major advantages of cloud computing.
Linux Essentials (Version 1.6) | Topic 1: The Linux Community and a Career in Open Source

8 | learning.lpi.org | Licensed under CC BY-NC-ND 4.0. | Version: 2022-01-14

Explorational Exercises
1. Considering cost and performance, which distributions are mostly suitable for a business that
aims to reduce licensing costs, while keeping performance at its highest? Explain why.

2. What are the major advantages of the Raspberry Pi and which functions can they take in
business?

3. What range of distributions does Amazon Cloud Services and Google Cloud offer? Name at least
three common ones and two different ones.

Linux Essentials (Version 1.6) | 1.1 Linux Evolution and Popular Operating Systems

Version: 2022-01-14 | Licensed under CC BY-NC-ND 4.0. | learning.lpi.org | 9

Summary
In this lesson you learned:
• What distributions does Linux have
• What are Linux embedded systems
• How are Linux embedded systems used
• Different applicabilities of Android
• Different uses of a Raspberry Pi
• What is Cloud Computing
• What role does Linux play in cloud computing

** 1.2 Major Open Source Applications
Weight: 2
Description: Awareness of major applications as well as their uses and development.
Key Knowledge Areas:
    Desktop applications
    Server applications
    Development languages
    Package management tools and repositories
The following is a partial list of the used files, terms and utilities:
    OpenOffice.org, LibreOffice, Thunderbird, Firefox, GIMP
    Nextcloud, ownCloud
    Apache HTTPD, NGINX, MariaDB, MySQL, NFS, Samba
    C, Java, JavaScript, Perl, shell, Python, PHP
    dpkg, apt-get, rpm, yum

** 1.3 Open Source Software and Licensing
Weight: 1
Description: Open communities and licensing Open Source Software for business.
Key Knowledge Areas:
    Open source philosophy
    Open source licensing
    Free Software Foundation (FSF), Open Source Initiative (OSI)
The following is a partial list of the used files, terms and utilities:
    Copyleft, Permissive
    GPL, BSD, Creative Commons
    Free Software, Open Source Software, FOSS, FLOSS
    Open source business models

** 1.4 ICT Skills and Working in Linux
Weight: 2
Description: Basic Information and Communication Technology (ICT) skills and working in Linux.
Key Knowledge Areas:
    Desktop skills
    Getting to the command line
    Industry uses of Linux, cloud computing and virtualization
The following is a partial list of the used files, terms and utilities:
    Using a browser, privacy concerns, configuration options, searching the web and saving content
    Terminal and console
    Password issues
    Privacy issues and tools
    Use of common open source applications in presentations and projects

* 2 finding your way on a linux system

** 2.1 Command Line Basics

Weight: 3

Description: Basics of using the Linux command line.

Key Knowledge Areas:

    Basic shell
    Command line syntax
    Variables
    Quoting

The following is a partial list of the used files, terms and utilities:

    Bash
    echo
    history
    PATH environment variable
    export
    type


** 2.2 Using the Command Line to Get Help

Weight: 2

Description: Running help commands and navigation of the various help systems.

Key Knowledge Areas:

    Man pages
    Info pages

The following is a partial list of the used files, terms and utilities:

    man
    info
    /usr/share/doc/
    locate


** 2.3 Using Directories and Listing Files

Weight: 2

Description: Navigation of home and system directories and listing files in various locations.

Key Knowledge Areas:

    Files, directories
    Hidden files and directories
    Home directories
    Absolute and relative paths

The following is a partial list of the used files, terms and utilities:

    Common options for ls
    Recursive listings
    cd
    . and ..
    home and ~


** 2.4 Creating, Moving and Deleting Files

Weight: 2

Description: Create, move and delete files and directories under the home directory.

Key Knowledge Areas:

    Files and directories
    Case sensitivity
    Simple globbing

The following is a partial list of the used files, terms and utilities:

    mv, cp, rm, touch
    mkdir, rmdir

* 3 the power of the command line
Topic 3: The Power of the Command Line
3.1 Archiving Files on the Command Line

Weight:  2

Description: Archiving files in the user home directory.

Key Knowledge Areas:

    Files, directories
    Archives, compression

The following is a partial list of the used files, terms and utilities:

    tar
    Common tar options
    gzip, bzip2, xz
    zip, unzip


3.2 Searching and Extracting Data from Files

Weight: 3

Description: Search and extract data from files in the home directory.

Key Knowledge Areas:

    Command line pipes
    I/O redirection
    Basic Regular Expressions using ., [ ], *, and ?

The following is a partial list of the used files, terms and utilities:

    grep
    less
    cat, head, tail
    sort
    cut
    wc


3.3 Turning Commands into a Script

Weight: 4

Description: Turning repetitive commands into simple scripts.

Key Knowledge Areas:

    Basic shell scripting
    Awareness of common text editors (vi and nano)

The following is a partial list of the used files, terms and utilities:

    #! (shebang)
    /bin/bash
    Variables
    Arguments
    for loops
    echo
    Exit status

* 4 the linux operating system
Topic 4: The Linux Operating System
4.1 Choosing an Operating System

Weight: 1

Description: Knowledge of major operating systems and Linux distributions.

Key Knowledge Areas:

    Differences between Windows, OS X and Linux
    Distribution life cycle management

The following is a partial list of the used files, terms and utilities:

    GUI versus command line, desktop configuration
    Maintenance cycles, beta and stable


4.2 Understanding Computer Hardware

Weight: 2

Description: Familiarity with the components that go into building desktop and server computers.

Key Knowledge Areas:

    Hardware

The following is a partial list of the used files, terms and utilities:

    Motherboards, processors, power supplies, optical drives, peripherals
    Hard drives, solid state disks and partitions, /dev/sd*
    Drivers


4.3 Where Data is Stored

Weight: 3

Description: Where various types of information are stored on a Linux system.

Key Knowledge Areas:

    Programs and configuration
    Processes
    Memory addresses
    System messaging
    Logging

The following is a partial list of the used files, terms and utilities:

    ps, top, free
    syslog, dmesg
    /etc/, /var/log/
    /boot/, /proc/, /dev/, /sys/


4.4 Your Computer on the Network

Weight: 2

Description: Querying vital networking configuration and determining the basic requirements for a computer on a Local Area Network (LAN).

Key Knowledge Areas:

    Internet, network, routers
    Querying DNS client configuration
    Querying network configuration

The following is a partial list of the used files, terms and utilities:

    route, ip route show
    ifconfig, ip addr show
    netstat, ss
    /etc/resolv.conf, /etc/hosts
    IPv4, IPv6
    ping
    host

* 5 security and file permissions
Topic 5: Security and File Permissions
5.1 Basic Security and Identifying User Types

Weight: 2

Description: Various types of users on a Linux system.

Key Knowledge Areas:

    Root and standard users
    System users

The following is a partial list of the used files, terms and utilities:

    /etc/passwd, /etc/shadow, /etc/group
    id, last, who, w
    sudo, su


5.2 Creating Users and Groups

Weight: 2

Description: Creating users and groups on a Linux system.

Key Knowledge Areas:

    User and group commands
    User IDs

The following is a partial list of the used files, terms and utilities:

    /etc/passwd, /etc/shadow, /etc/group, /etc/skel/
    useradd, groupadd
    passwd


5.3 Managing File Permissions and Ownership

Weight: 2

Description: Understanding and manipulating file permissions and ownership settings.

Key Knowledge Areas:

    File and directory permissions and ownership

The following is a partial list of the used files, terms and utilities:

    ls -l, ls -a
    chmod, chown


5.4 Special Directories and Files

Weight: 1

Description: Special directories and files on a Linux system including special permissions.

Key Knowledge Areas:

    Using temporary files and directories
    Symbolic links

The following is a partial list of the used files, terms and utilities:

    /tmp/, /var/tmp/ and Sticky Bit
    ls -d
    ln -s
