:PROPERTIES:
:ID:       bbad4e71-066d-4231-953a-3b5ed0891141
:END:
#+title: #+title: css
#+date: [2022-05-31 Tue 11:20]

css :: cascading style sheets

use to style the html content.

Ruleset Terms:

    Selector—The beginning of the ruleset used to target the element that will be styled.
    Declaration Block—The code in-between (and including) the curly braces ({ }) that contains the CSS declaration(s).
    Declaration—The group name for a property and value pair that applies a style to the selected element.
    Property—The first part of the declaration that signifies what visual characteristic of the element is to be modified.
    Value—The second part of the declaration that signifies the value of the property.

Inline Style Terms:

    Opening Tag—The start of an HTML element. This is the element that will be styled.
    Attribute—The style attribute is used to add CSS inline styles to an HTML element.
    Declaration—The group name for a property and value pair that applies a style to the selected element.
    Property—The first part of the declaration that signifies what visual characteristic of the element is to be modified.
    Value—The second part of the declaration that signifies the value of the property.



    The basic anatomy of CSS syntax written for both inline styles and stylesheets.
    Some commonly used CSS terms, such as ruleset, selector, and declaration.
    CSS inline styles can be written inside the opening HTML tag using the style attribute.
    Inline styles can be used to style HTML, but it is not the best practice.
    An internal stylesheet is written using the <style> element inside the <head> element of an HTML file.
    Internal stylesheets can be used to style HTML but are also not best practice.
    An external stylesheet separates CSS code from HTML, by using the “.css”.file extension.
    External stylesheets are the best approach when it comes to using HTML and CSS.
    External stylesheets are linked to HTML using the <link> element.
