:PROPERTIES:
:ID:       bbad4e71-066d-4231-953a-3b5ed0891141
:END:
#+title: CSS
#+date: [2022-05-31 Tue 11:20]

css :: cascading style sheets

use to style the html content.


Cascading Style Sheets
A programming language designed to supplement HTML by adding formatting, design, and style details to web pages
Style sheet language
A class of computer languages that express and explain how a markup language or other structured document content should get presented

css anatomy
Ruleset Terms:

    Selector—The beginning of the ruleset used to target the element that will be styled.
    Declaration Block—The code in-between (and including) the curly braces ({ }) that contains the CSS declaration(s).
    Declaration—The group name for a property and value pair that applies a style to the selected element.
    Property—The first part of the declaration that signifies what visual characteristic of the element is to be modified.
    Value—The second part of the declaration that signifies the value of the property.

Inline Style Terms:

    Opening Tag—The start of an HTML element. This is the element that will be styled.
    Attribute—The style attribute is used to add CSS inline styles to an HTML element.
    Declaration—The group name for a property and value pair that applies a style to the selected element.
    Property—The first part of the declaration that signifies what visual characteristic of the element is to be modified.
    Value—The second part of the declaration that signifies the value of the property.



    The basic anatomy of CSS syntax written for both inline styles and stylesheets.
    Some commonly used CSS terms, such as ruleset, selector, and declaration.
    CSS inline styles can be written inside the opening HTML tag using the style attribute.
    Inline styles can be used to style HTML, but it is not the best practice.
    An internal stylesheet is written using the <style> element inside the <head> element of an HTML file.
    Internal stylesheets can be used to style HTML but are also not best practice.
    An external stylesheet separates CSS code from HTML, by using the “.css”.file extension.
    External stylesheets are the best approach when it comes to using HTML and CSS.
    External stylesheets are linked to HTML using the <link> element.

Cascading Style Sheets or CSS is a language web developers use to style the HTML
content on a web page.

inline style and internal stylesheet are not best practices

etup and Syntax
Review

Great work so far! By understanding how to incorporate CSS code into your HTML file, as well as learning some of the key terms, you’re on your way to creating spectacular websites with HTML and CSS.

Let’s review what you learned so far:

    The basic anatomy of CSS syntax written for both inline styles and stylesheets.
    Some commonly used CSS terms, such as ruleset, selector, and declaration.
    CSS inline styles can be written inside the opening HTML tag using the style attribute.
    Inline styles can be used to style HTML, but it is not the best practice.
    An internal stylesheet is written using the <style> element inside the <head> element of an HTML file.
    Internal stylesheets can be used to style HTML but are also not best practice.
    An external stylesheet separates CSS code from HTML, by using the “.css”.file extension.
    External stylesheets are the best approach when it comes to using HTML and CSS.
    External stylesheets are linked to HTML using the <link> element.


Selectors
Review

Throughout this lesson, you learned how to select HTML elements with CSS and apply styles to them. Let’s review what you learned:

    CSS can select HTML elements by type, class, ID, and attribute.
    All elements can be selected using the universal selector.
    An element can have different states using the pseudo-class selector.
    Multiple CSS classes can be applied to one HTML element.
    Classes can be reusable, while IDs can only be used once.
    IDs are more specific than classes, and classes are more specific than type. That means IDs will override any styles from a class, and classes will override any styles from a type selector.
    Multiple selectors can be chained together to select an element. This raises the specificity but can be necessary.
    Nested elements can be selected by separating selectors with a space.
    Multiple unrelated selectors can receive the same styles by separating the selector names with commas.

Great work this lesson. With this knowledge, you’ll be able to use CSS to change the look and feel of websites to make them look great!

Review Visual Rules

Incredible work! You used CSS to alter text and images on a website. Throughout this lesson, you learned concepts including:

    The font-family property defines the typeface of an element.
    font-size controls the size of text displayed.
    font-weight defines how thin or thick text is displayed.
    The text-align property places text in the left, right, or center of its parent container.
    Text can have two different color attributes: color and background-color. color defines the color of the text, while background-color defines the color behind the text.
    CSS can make an element transparent with the opacity property.
    CSS can also set the background of an element to an image with the background-image property.
    The !important flag will override any style, however it should almost never be used, as it is extremely difficult to override.

Notably, CSS can add many elements to HTML, such as those listed below.

    Text: CSS assigns specific fonts, text sizes, alignments, and colors to text.

    Media: CSS assigns the image sizes for images on a web page, and it can add rounded corners and fancy borders to those images.

    Links: CSS assigns colors to links.

    Containers: CSS assigns the height and width of containers on a web page, as well as the colors or images that are used in the background to provide structure and style.

CSS rule
    Also called a ruleset, the entire block of CSS code assigned to style an HTML element
CSS selector
    Code that identifies what HTML element should be affected by the declaration block that follows the selector
CSS property
    The general category or type of stylistic change that you'd like to make
CSS value
    The specific change that you want to make, such as pixel size or color
CSS declaration
    The property and value applied to the selector
Hex color code
    Also called hex value, an alphanumeric code used to specify a color value

CSS rulesets

Like HTML, CSS has a particular syntax. To properly follow this syntax, you'll need to learn how it works.

CSS is a collection of rulesets, which are commonly referred to as rules. These rules define what changes are applied to the HTML file. This image shows a single rule, which has several components: a selector, a property, a declaration, and a value.
Labeled CSS rule with selector as well as a declaration made up of a property and a value.

Here's a quick rundown based on the image above. This will give you a high-level overview before you dive deeper.

    Rule or ruleset: This is the entire block of CSS code assigned to style an HTML element.

    Selector: This is the name of the HTML element that will be styled.

    Property: This is a set or family of attributes, or options, that you can change.

    Value: This is the specific change you want to make, such as pixel size or color.

    Declaration: This consists of both the property and the value assigned to the selector.

Selectors and declarations

A selector defines what element in the code should be affected by the declaration block that follows the selector. The selector refers to a specific HTML element, like a p element in the image above. In this case, every p element, or HTML paragraph, on the page will be styled by the information provided in the declaration block.

The declaration block begins and ends with curly brackets {}. Each line inside of the {} represents a separate declaration, each of which applies a particular style or format to the referenced element. For example, the CSS code below has two declarations. What does each one do?

As you can see, the declarations in the example above change the color and size of the text. Like in HTML code, spaces and hard returns in CSS code have no effect on how text is presented on a web page. But spaces and hard returns can provide visual organization in the code, which makes the code easier to read and understand.
Properties and values

Each declaration is made up of two components: a property and a value. At its most basic level, a CSS property is the general category or type of stylistic change you'd like to make. The value then specifies exactly what style you'd like to apply.

There are hundreds of CSS properties and values. The CSS Properties Reference from Mozilla is a valuable resource that shares only the most common properties. And as you'll see, it's still a long list! In fact, you will regularly discover new CSS properties and values over the course of your career.

In a declaration, the property is named first. It's followed by a colon :, then the value, and then a semicolon ; at the end. Structurally, declarations look like this: property: value;. One of the best ways to learn about properties and values is to see examples of how they work. Check out the one below. What do these declarations do?

h1 {

  color: white;

  font-family: 'Times New Roman';

  font-size: 16px;

}

As you might've guessed, the color property refers to text color, and the value white sets the color of the text to white. (It's worth noting that you'll often see hex color codes in the value position; you'll learn about those later on in this lesson.) The font-family applies a specific font to the text. Arial and Times New Roman are both common fonts found on nearly every computer. Font names with more than one word are wrapped in quotes, like 'this', to help the code read the font name properly.

The font-size property refers to how big or small the text will be on the page. The px value stands for pixels, and it sets the exact text size. Pixels are a common measurement for text on the web. But as you learn more about sizing, you'll discover other measurements that are particularly useful in sizing HTML elements.

    color

        red

        blue

        green

        pink

        yellow

        orange

        black

    font-family

        Arial

        'Arial Black'

        'Comic Sans MS'

        Impact

        'Trebuchet MS'

        'Times New Roman'

        Georgia

        Webdings

        Wingdings

    font-size

        Practice using sizes that are between 8px and 108px.


    Serif: Serif fonts are often used for headings. The letters in these fonts have little tapered ends or tails, which add a stylistic accent to text and make letters and characters more attractive at larger sizes.

    Sans-serif: Sans-serif fonts are often used for paragraph text on websites. They have minimal flaring or tapering at the ends of letters, making smaller text easier to read.

    Monospace: These fonts are often used for code samples, and all of the letters have the same width.

    Cursive: This type of font has a playful, handwritten style, which can feel more emphatic than italics.

    Fantasy: This type of font has a whimsical, decorative style. But use this as a fallback with care; it's more limited than other font groups.


    Serif: Serif fonts are often used for headings. The letters in these fonts have little tapered ends or tails, which add a stylistic accent to text and make letters and characters more attractive at larger sizes.

    Sans-serif: Sans-serif fonts are often used for paragraph text on websites. They have minimal flaring or tapering at the ends of letters, making smaller text easier to read.

    Monospace: These fonts are often used for code samples, and all of the letters have the same width.

    Cursive: This type of font has a playful, handwritten style, which can feel more emphatic than italics.

    Fantasy: This type of font has a whimsical, decorative style. But use this as a fallback with care; it's more limited than other font groups.

As you explore CSS further, you'll likely want to play around with other text-related properties. Here are some examples:

    font-style: This is how you can change the stylistic formatting of the font, such as adding italics (italic or oblique).

    font-weight: This is how you set the thinness or thickness of a font. There are usually values from 100 to 900 available.

    letter-spacing: This is how you determine the proximity of individual letters by increasing or decreasing the space between them, measured in pixels. For example, a value of 1px is fairly normal, or a value of -3px will pull the letters closer together.

    line-height: This is how you increase or decrease the space between lines of text. For example, you could apply 20px of space between lines of text.

    text-align: This property allows you to realign text to be center, left, right, or justified.

    text-decoration: This allows you to add additional formatting, like underline, overline (text with a horizontal line above it, often used in math notation), or line-through (also known as strikethrough).

    text-transform: This allows you to change the case of the letters, such as uppercase and lowercase.
